CREATE TABLE recommend_requests (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES recommend_users(id) ON DELETE CASCADE,
    product TEXT NOT NULL,
    category TEXT NOT NULL,
    info TEXT NOT NULL,
    date DATE NOT NULL
);